from_db_class_name: '<DB_CLASS_NAME>' # currently supports mongodb(MongodbDatabase) and redis(RedisDatabase)
to_db_class_name: '<DB_CLASS_NAME>' # currently supports mongodb(MongodbDatabase) and redis(RedisDatabase)
from_db_host: '<FROM_DB_HOST>'
from_db_port: '<FROM_DB_PORT>'
to_db_host: '<TO_DB_HOST>'
to_db_port: '<TO_DB_PORT>' # 27017 for mongodb, 6379 for redis
time_before: '<TIME_BEFORE>' # time before in seconds